name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run bash tests
        run: |
          SHELL_CMD="-c ./run_tests.sh" make bash zsh

      - name: Run zsh tests
        run: |
          SHELL_CMD="-c ./run_tests.sh" make zsh

      - name: Run fish tests
        run: |
          SHELL_CMD="-c ./run_tests.fish" make fish

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: |
          sudo apt-get install shellcheck

      - name: Run linter
        run: |
          make lint
